name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
      - uses: julia-actions/setup-julia@master
      - run: julia -e '
          using Pkg;
          Pkg.activate(".");
          Pkg.instantiate();

          using NodeJS;
          run(`$(npm_cmd()) install highlight.js`);

          using Franklin;

          optimize()'
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: __site