name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
      - uses: julia-actions/setup-julia@master
      - run: julia -e '
          using Pkg;
          Pkg.activate(".");
          Pkg.instantiate();

          using NodeJS;
          run(`$(npm_cmd()) install highlight.js`);

          using Franklin;

          optimize()'
      - uses: actions/upload-pages-artifact@main
        with:
          path: __site
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@main