name: Image

on:
  push:
    branches: [main]
    paths:
      - ".devcontainer/**"
      - "Project.toml"
      - "Manifest.toml"
      - "Dokcerfile"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: docker/setup-buildx-action@master
      - uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/franklin-dev:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/franklin-dev:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/franklin-dev:cache,mode=max
